sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: fxm-java-web-springboot
  redis:
    host: localhost
    port: 6379
    database: 01
  wechat:
    appid:
    secret: